services:

  ### DATABASE (mysql)
  db:
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/perm.sql:/docker-entrypoint-initdb.d/perm.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h db -u root --password=$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 25s
      timeout: 70s
      retries: 1500
  
  ### BACKEND (django)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 backend.wsgi:application"
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy


  ### FRONTEND (nextjs)
  frontend_nextjs:
    build:
      context: ./frontend_nextjs
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend_nextjs:/app

  ### PORT FORWARDING (nginx)
  nginx: 
    image: nginx:latest
    container_name: nginx
    depends_on:
      - frontend_nextjs
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro


# Storing data persistently
volumes:
  mysql_data:
