# Generated by Django 5.1.7 on 2025-03-23 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=255, unique=True)),
                ('email', models.CharField(db_column='Email', max_length=255, unique=True)),
                ('passwordhash', models.CharField(db_column='PasswordHash', max_length=64)),
                ('phone_no', models.CharField(db_column='PhoneNo', help_text='Enter a valid phone number with up to 15 digits.', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
            options={
                'db_table': 'auth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTokenAuth',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('token', models.CharField(db_column='token', max_length=40, unique=True)),
                ('request_count', models.IntegerField(db_column='request_count', default=0)),
                ('last_request_date', models.DateField(blank=True, db_column='last_request_date', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created')),
                ('otp', models.IntegerField(db_column='OTP', help_text='OTP must be a 7-digit number between 1000000 and 9999999.', validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(9999999)])),
                ('email_verified', models.BooleanField(db_column='EmailVerified', default=False)),
                ('phone_verified', models.BooleanField(db_column='PhoneVerified', default=False)),
            ],
            options={
                'db_table': 'usertokenauth',
                'managed': False,
            },
        ),
    ]
