# Generated by Django 5.0.6 on 2024-10-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTokenAuth',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('token', models.CharField(db_column='token', max_length=40, unique=True)),
                ('request_count', models.IntegerField(db_column='request_count', default=0)),
                ('last_request_date', models.DateField(blank=True, db_column='last_request_date', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created')),
            ],
            options={
                'db_table': 'usertokenauth',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
