# Generated by Django 5.1.4 on 2024-12-18 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_usertokenauth_delete_authtoken'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auth',
            table='Auth',
        ),
        migrations.AlterModelTable(
            name='usertokenauth',
            table='UserTokenAuth',
        ),
    ]
