# Generated by Django 5.1.4 on 2024-12-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_auth_table_alter_usertokenauth_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auth',
            table='auth',
        ),
        migrations.AlterModelTable(
            name='usertokenauth',
            table='usertokenauth',
        ),
    ]
